/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.c
 *
 * Description: Source file for the ultrasonic sensor
 *
 * Author: Mohamed Hassan
 *
 *******************************************************************************/
#include"ultrasonic_sensor.h"
#include "gpio.h"
#include "icu.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include<util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* Global variables to hold the address of the call back function in the application */
static Icu_ConfigType myConfig = {F_CPU_8,RISING};
static uint16 g_echoTime = 0;



/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description : Function to initialize the ultrasonic sensor driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	Icu_init(&myConfig);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_SENSOR_TRIGGER_PORT_ID, ULTRASONIC_SENSOR_TRIGGER_PIN_ID, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_SENSOR_TRIGGER_PORT_ID,ULTRASONIC_SENSOR_TRIGGER_PIN_ID,LOGIC_LOW);
	//GPIO_setupPinDirection(ULTRASONIC_SENSOR_ECHO_PORT_ID, ULTRASONIC_SENSOR_ECHO_PIN_ID, PIN_INPUT);
}

/*
 * Description : Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_SENSOR_TRIGGER_PORT_ID,ULTRASONIC_SENSOR_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(ULTRASONIC_SENSOR_PULSE_DELAY);
	GPIO_writePin(ULTRASONIC_SENSOR_TRIGGER_PORT_ID,ULTRASONIC_SENSOR_TRIGGER_PIN_ID,LOGIC_LOW);
}
/*
 * Description :
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	2. Start the measurements by the ICU from this moment.
 * 	3. Return the measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();
//	while(GET_BIT(ULTRASONIC_SENSOR_ECHO_PORT_ID,ULTRASONIC_SENSOR_ECHO_PIN_ID)!=0);
	uint16 total_distance = (g_echoTime / 58.8);
    return total_distance;

}

/*
 * Description :
 * 	1. This is the call back function called by the ICU driver.
 * 	2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	static uint16 g_edgeCount = 0;
	g_edgeCount++;
	if(g_edgeCount==1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	if(g_edgeCount==2)
	{
		g_echoTime=Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}

}

